### ISSUE TITLE
Vue router

### ISSUE THREAD

**Issue by Tofandel** [niutech/vue-in-web-worker#2]
Is there any way to get this to play nice with vue router?
The web worker doesn't seem to have access to document.location.href

Sadly not much use without it

Error thrown in

```
document.location.href.replace(document.location.hash,"")
```

It seems to be a polyfill from `document.currentScript` which is itself bundled because of the vue util `setPublicPath`

**Comment by niutech** [comment]
Sorry, but `document.location` is [not supported by worker-dom](https://github.com/ampproject/worker-dom/blob/main/web_compat_table.md), so we cannot use it. Please file an issue in [worker-dom](https://github.com/ampproject/worker-dom/).
